// filepath: lib/data/services/firebase_sync_service.dart

import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:rxdart/rxdart.dart';
import 'package:tenniscourtcare/data/database/app_database.dart';
import 'package:tenniscourtcare/data/mappers/event_mapper.dart';
import 'package:tenniscourtcare/data/mappers/maintenance_mapper.dart';
import 'package:tenniscourtcare/domain/entities/sync_status.dart';
import 'package:tenniscourtcare/data/services/firebase_terrain_service.dart';
import 'package:tenniscourtcare/data/services/firebase_maintenance_service.dart';
import 'package:tenniscourtcare/data/services/firebase_stock_service.dart';
import 'package:tenniscourtcare/data/services/firebase_event_service.dart';

class FirebaseSyncService {
  final FirebaseFirestore _firestore;
  final AppDatabase _db;

  late final FirebaseTerrainService _terrainService;
  late final FirebaseMaintenanceService _maintenanceService;
  late final FirebaseStockService _stockService;
  late final FirebaseEventService _eventService;

  final BehaviorSubject<Map<String, SyncStatus>> _syncStatusController =
      BehaviorSubject.seeded({
        'terrains': SyncStatus.local,
        'maintenances': SyncStatus.local,
        'stock': SyncStatus.local,
        'events': SyncStatus.local,
      });

  FirebaseSyncService(this._firestore, this._db) {
    _terrainService = FirebaseTerrainService(_firestore);
    _maintenanceService = FirebaseMaintenanceService(_firestore);
    _stockService = FirebaseStockService(_firestore);
    _eventService = FirebaseEventService(_firestore);
  }

  Stream<Map<String, SyncStatus>> watchSyncStatus() => _syncStatusController.stream;

  void _updateStatus(String key, SyncStatus status) {
    final current = Map<String, SyncStatus>.from(_syncStatusController.value);
    current[key] = status;
    _syncStatusController.add(current);
  }

  Future<void> syncAll() async {
    await Future.wait([
      syncTerrains(),
      syncMaintenances(),
      syncStock(),
      syncEvents(),
    ]);
  }

  Future<void> syncTerrains() async {
    _updateStatus('terrains', SyncStatus.syncing);
    try {
      final all = await _db.getAllTerrains();
      final unsynced = await _terrainService.getUnsyncedTerrains(all);

      for (final item in unsynced) {
        await _terrainService.uploadTerrainToFirestore(item);
        // Update local status
        final updated = item.copyWith(syncStatus: SyncStatus.synced, firebaseId: item.firebaseId);
        // Note: firebaseId might need to be set if generated by Firestore, but here we assume logic uses local ID or existing firebaseId.
        // If upload generated an ID, we should capture it. But uploadTerrainToFirestore doesn't return ID.
        // Assuming ID handling is consistent (custom ID or pre-assigned).
        await _db.updateTerrain(updated);
      }
      _updateStatus('terrains', SyncStatus.synced);
    } catch (e) {
      print('Sync Terrains Error: $e');
      _updateStatus('terrains', SyncStatus.error);
    }
  }

  Future<void> syncMaintenances() async {
    _updateStatus('maintenances', SyncStatus.syncing);
    try {
      // Need to fetch all maintenances. AppDatabase doesn't have getAllMaintenances helper?
      // It has getMaintenancesForTerrain, watchMaintenancesInRange...
      // I might need to add a method to AppDatabase or use what's available.
      // Since I can't easily modify AppDatabase interface (Phase 4/5 strict scope?),
      // I'll check if there is a way.
      // AppDatabase has `select(maintenances).get()`. But I can't access it externally if not exposed?
      // `AppDatabase` class has `select` but it's protected/mixed in?
      // Usually `select` is available inside the class.
      // External access to `select`? No.
      // So I must rely on public methods.
      // `getAllTerrains` exists.
      // `getMaintenancesForTerrain(id)`.
      // I can iterate terrains and get maintenances.

      final terrains = await _db.getAllTerrains();
      for (final t in terrains) {
        final maintenances = await _db.getMaintenancesForTerrain(t.id);
        final unsynced = await _maintenanceService.getUnsyncedMaintenances(maintenances);

        for (final item in unsynced) {
          await _maintenanceService.uploadMaintenanceToFirestore(item);
          final updated = item.copyWith(syncStatus: SyncStatus.synced);
          await _db.updateMaintenance(updated.toCompanion());
        }
      }
      _updateStatus('maintenances', SyncStatus.synced);
    } catch (e) {
      print('Sync Maintenances Error: $e');
      _updateStatus('maintenances', SyncStatus.error);
    }
  }

  Future<void> syncStock() async {
    _updateStatus('stock', SyncStatus.syncing);
    try {
      // AppDatabase has `watchAllStockItems` (Stream).
      // Does it have `getAllStockItems` (Future)?
      // `select(stockItems).get()` is likely not exposed as `getAllStockItems`.
      // `watchAllStockItems` returns Stream. I can take first.
      final all = await _db.watchAllStockItems().first;
      final unsynced = await _stockService.getUnsyncedStockItems(all);

      for (final item in unsynced) {
        await _stockService.uploadStockItemToFirestore(item);
        final updated = item.copyWith(syncStatus: SyncStatus.synced);
        await _db.updateStockItem(updated);
      }
      _updateStatus('stock', SyncStatus.synced);
    } catch (e) {
      print('Sync Stock Error: $e');
      _updateStatus('stock', SyncStatus.error);
    }
  }

  Future<void> syncEvents() async {
    _updateStatus('events', SyncStatus.syncing);
    try {
      // AppDatabase `events` table exists.
      // Need method to get all events.
      // AppDatabase file read didn't show `getAllEvents` or `watchAllEvents`.
      // It showed `Events` table definition in `tables/events_table.dart`.
      // But `AppDatabase` class in `app_database.dart` might not have methods for Events yet?
      // I read `app_database.dart` earlier.
      // It has `getAllTerrains`, `getMaintenances...`, `insertUser`, `watchAllStockItems`.
      // It does NOT seem to have Event methods?
      // Wait, `from < 5` created `events`.
      // But no getter methods in the `AppDatabase` class body I saw?
      // Let's re-read `app_database.dart` to be sure.
      // Use `read_file` if needed, but I have it in context.
      // I see `Future<void> _seedStockItems()`.
      // I see `Future<domu.UserEntity?> getUserByEmail...`.
      // I see `Stream<List<doms.StockItem>> watchAllStockItems()`.
      // I see `Future<List<dom.Terrain>> getAllTerrains()`.
      // I see `Future<List<domm.Maintenance>> getMaintenancesForTerrain...`.
      // I DO NOT see methods for Events in `AppDatabase` body in the snippet I read.

      // If `AppDatabase` doesn't expose Events, I can't sync them using `_db` public API.
      // This is a problem.
      // But I am allowed to modify `app_database.dart`?
      // "PHASE 4 + 5... 9 fichiers". `app_database.dart` is NOT in the list.
      // But `AppDatabase` is passed to `FirebaseSyncService`.
      // Maybe I should assume `AppDatabase` has `getAllEvents`?
      // Or maybe I should use `(select(_db.events)..get())`?
      // Drift database instance allows `select(events)` if `events` getter is public.
      // `AppDatabase` extends `_$AppDatabase`. `_$AppDatabase` has `events` getter.
      // So `_db.events` is accessible!
      // And `_db.select(_db.events)` is accessible!
      // So I can write queries here if I import `drift`.

      final query = _db.select(_db.events);
      final rows = await query.get();
      // Need to map rows to domain.
      // `row.toDomain()` using mapper extension.
      // Need to import `event_mapper.dart`.

      final all = rows.map((r) => r.toDomain()).toList();
      final unsynced = await _eventService.getUnsyncedEvents(all);

      for (final item in unsynced) {
        await _eventService.uploadEventToFirestore(item);
        final updated = item.copyWith(syncStatus: SyncStatus.synced);
        // Update in DB.
        // `_db.update(_db.events).replace(updated.toCompanion())`
        await _db.update(_db.events).replace(updated.toCompanion());
      }
      _updateStatus('events', SyncStatus.synced);
    } catch (e) {
      print('Sync Events Error: $e');
      _updateStatus('events', SyncStatus.error);
    }
  }
}
