// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKZhejG5WZBGJLxbCizD_V7S18pqvfuE',
    appId: '1:476144130552:web:49ea86a530f26d6fcd1e0d',
    messagingSenderId: '476144130552',
    projectId: 'tenniscourtcare',
    authDomain: 'tenniscourtcare.firebaseapp.com',
    storageBucket: 'tenniscourtcare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTFhSzpzPiZjVaGFlCvqxG2uOqtChm_c',
    appId: '1:476144130552:android:263928f28aa2d933cd1e0d',
    messagingSenderId: '476144130552',
    projectId: 'tenniscourtcare',
    storageBucket: 'tenniscourtcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfgp4-2TyJ8-mjj4CX_1l_Yy1wBOMchng',
    appId: '1:476144130552:ios:a4be5e075ab71de1cd1e0d',
    messagingSenderId: '476144130552',
    projectId: 'tenniscourtcare',
    storageBucket: 'tenniscourtcare.firebasestorage.app',
    iosBundleId: 'com.example.tenniscourtcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfgp4-2TyJ8-mjj4CX_1l_Yy1wBOMchng',
    appId: '1:476144130552:ios:a4be5e075ab71de1cd1e0d',
    messagingSenderId: '476144130552',
    projectId: 'tenniscourtcare',
    storageBucket: 'tenniscourtcare.firebasestorage.app',
    iosBundleId: 'com.example.tenniscourtcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKZhejG5WZBGJLxbCizD_V7S18pqvfuE',
    appId: '1:476144130552:web:0a4f59a4cbada74bcd1e0d',
    messagingSenderId: '476144130552',
    projectId: 'tenniscourtcare',
    authDomain: 'tenniscourtcare.firebaseapp.com',
    storageBucket: 'tenniscourtcare.firebasestorage.app',
  );
}
