// Mocks generated by Mockito 5.4.6 from annotations
// in tenniscourtcare/test/data/services/firebase_cache_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i16;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:cloud_firestore_platform_interface/cloud_firestore_platform_interface.dart'
    as _i7;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:firebase_core/firebase_core.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:tenniscourtcare/data/database/app_database.dart' as _i3;
import 'package:tenniscourtcare/domain/entities/app_event.dart' as _i15;
import 'package:tenniscourtcare/domain/entities/maintenance.dart' as _i13;
import 'package:tenniscourtcare/domain/entities/stock_item.dart' as _i12;
import 'package:tenniscourtcare/domain/entities/terrain.dart' as _i14;
import 'package:tenniscourtcare/domain/entities/user_entity.dart' as _i10;
import 'package:tenniscourtcare/domain/enums/role.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TerrainsTable_1 extends _i1.SmartFake
    implements _i3.$TerrainsTable {
  _Fake$TerrainsTable_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MaintenancesTable_2 extends _i1.SmartFake
    implements _i3.$MaintenancesTable {
  _Fake$MaintenancesTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StockItemsTable_3 extends _i1.SmartFake
    implements _i3.$StockItemsTable {
  _Fake$StockItemsTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_4 extends _i1.SmartFake implements _i3.$UsersTable {
  _Fake$UsersTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EventsTable_5 extends _i1.SmartFake implements _i3.$EventsTable {
  _Fake$EventsTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StockMovementsTable_6 extends _i1.SmartFake
    implements _i3.$StockMovementsTable {
  _Fake$StockMovementsTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AuditLogsTable_7 extends _i1.SmartFake
    implements _i3.$AuditLogsTable {
  _Fake$AuditLogsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LoginAttemptsTable_8 extends _i1.SmartFake
    implements _i3.$LoginAttemptsTable {
  _Fake$LoginAttemptsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$OtpRecordsTable_9 extends _i1.SmartFake
    implements _i3.$OtpRecordsTable {
  _Fake$OtpRecordsTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ReservationsTable_10 extends _i1.SmartFake
    implements _i3.$ReservationsTable {
  _Fake$ReservationsTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_11 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_12 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_13 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_14 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_15 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_16 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_17 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_18 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_19 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_20<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_21<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_22<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_23<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_24<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_25<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_26<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_27<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_28 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_29 extends _i1.SmartFake implements _i6.FirebaseApp {
  _FakeFirebaseApp_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_30 extends _i1.SmartFake implements _i7.Settings {
  _FakeSettings_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_31<T extends Object?> extends _i1.SmartFake
    implements _i8.CollectionReference<T> {
  _FakeCollectionReference_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_32 extends _i1.SmartFake implements _i8.WriteBatch {
  _FakeWriteBatch_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_33 extends _i1.SmartFake
    implements _i8.LoadBundleTask {
  _FakeLoadBundleTask_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_34<T1 extends Object?> extends _i1.SmartFake
    implements _i8.QuerySnapshot<T1> {
  _FakeQuerySnapshot_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_35<T extends Object?> extends _i1.SmartFake
    implements _i8.Query<T> {
  _FakeQuery_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_36<T extends Object?> extends _i1.SmartFake
    implements _i8.DocumentReference<T> {
  _FakeDocumentReference_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_37 extends _i1.SmartFake
    implements _i8.FirebaseFirestore {
  _FakeFirebaseFirestore_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAggregateQuery_38 extends _i1.SmartFake
    implements _i8.AggregateQuery {
  _FakeAggregateQuery_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_39 extends _i1.SmartFake
    implements _i8.SnapshotMetadata {
  _FakeSnapshotMetadata_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentSnapshot_40<T1 extends Object?> extends _i1.SmartFake
    implements _i8.DocumentSnapshot<T1> {
  _FakeDocumentSnapshot_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$TerrainsTable get terrains =>
      (super.noSuchMethod(
            Invocation.getter(#terrains),
            returnValue: _Fake$TerrainsTable_1(
              this,
              Invocation.getter(#terrains),
            ),
          )
          as _i3.$TerrainsTable);

  @override
  _i3.$MaintenancesTable get maintenances =>
      (super.noSuchMethod(
            Invocation.getter(#maintenances),
            returnValue: _Fake$MaintenancesTable_2(
              this,
              Invocation.getter(#maintenances),
            ),
          )
          as _i3.$MaintenancesTable);

  @override
  _i3.$StockItemsTable get stockItems =>
      (super.noSuchMethod(
            Invocation.getter(#stockItems),
            returnValue: _Fake$StockItemsTable_3(
              this,
              Invocation.getter(#stockItems),
            ),
          )
          as _i3.$StockItemsTable);

  @override
  _i3.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_4(this, Invocation.getter(#users)),
          )
          as _i3.$UsersTable);

  @override
  _i3.$EventsTable get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _Fake$EventsTable_5(this, Invocation.getter(#events)),
          )
          as _i3.$EventsTable);

  @override
  _i3.$StockMovementsTable get stockMovements =>
      (super.noSuchMethod(
            Invocation.getter(#stockMovements),
            returnValue: _Fake$StockMovementsTable_6(
              this,
              Invocation.getter(#stockMovements),
            ),
          )
          as _i3.$StockMovementsTable);

  @override
  _i3.$AuditLogsTable get auditLogs =>
      (super.noSuchMethod(
            Invocation.getter(#auditLogs),
            returnValue: _Fake$AuditLogsTable_7(
              this,
              Invocation.getter(#auditLogs),
            ),
          )
          as _i3.$AuditLogsTable);

  @override
  _i3.$LoginAttemptsTable get loginAttempts =>
      (super.noSuchMethod(
            Invocation.getter(#loginAttempts),
            returnValue: _Fake$LoginAttemptsTable_8(
              this,
              Invocation.getter(#loginAttempts),
            ),
          )
          as _i3.$LoginAttemptsTable);

  @override
  _i3.$OtpRecordsTable get otpRecords =>
      (super.noSuchMethod(
            Invocation.getter(#otpRecords),
            returnValue: _Fake$OtpRecordsTable_9(
              this,
              Invocation.getter(#otpRecords),
            ),
          )
          as _i3.$OtpRecordsTable);

  @override
  _i3.$ReservationsTable get reservations =>
      (super.noSuchMethod(
            Invocation.getter(#reservations),
            returnValue: _Fake$ReservationsTable_10(
              this,
              Invocation.getter(#reservations),
            ),
          )
          as _i3.$ReservationsTable);

  @override
  _i3.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_11(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$AppDatabaseManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_12(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_13(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_14(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_15(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i9.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_16(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_17(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_18(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<void> upsertTerrain(_i3.TerrainsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsertTerrain, [companion]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTerrainByFirebaseId(String? firebaseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTerrainByFirebaseId, [firebaseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertMaintenance(_i3.MaintenancesCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsertMaintenance, [companion]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMaintenanceByFirebaseId(String? firebaseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMaintenanceByFirebaseId, [firebaseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertStockItem(_i3.StockItemsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsertStockItem, [companion]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteStockItemByFirebaseId(String? firebaseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStockItemByFirebaseId, [firebaseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> upsertEvent(_i3.EventsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEvent, [companion]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEventByFirebaseId(String? firebaseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEventByFirebaseId, [firebaseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i10.UserEntity?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i5.Future<_i10.UserEntity?>.value(),
          )
          as _i5.Future<_i10.UserEntity?>);

  @override
  _i5.Future<_i10.UserEntity?> getUserByFirestoreUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByFirestoreUid, [uid]),
            returnValue: _i5.Future<_i10.UserEntity?>.value(),
          )
          as _i5.Future<_i10.UserEntity?>);

  @override
  _i5.Future<_i10.UserEntity?> getUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i5.Future<_i10.UserEntity?>.value(),
          )
          as _i5.Future<_i10.UserEntity?>);

  @override
  _i5.Future<_i3.UserRow?> getUserRowByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRowByEmail, [email]),
            returnValue: _i5.Future<_i3.UserRow?>.value(),
          )
          as _i5.Future<_i3.UserRow?>);

  @override
  _i5.Future<List<_i10.UserEntity>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<List<_i10.UserEntity>>.value(
              <_i10.UserEntity>[],
            ),
          )
          as _i5.Future<List<_i10.UserEntity>>);

  @override
  _i5.Future<int> insertUser(_i3.UsersCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateUserRole(int? userId, _i11.Role? newRole) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [userId, newRole]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateLastLogin(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [userId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countUsersByRole(_i11.Role? role) =>
      (super.noSuchMethod(
            Invocation.method(#countUsersByRole, [role]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> countUsers() =>
      (super.noSuchMethod(
            Invocation.method(#countUsers, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateUserPassword(int? userId, String? newHash) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPassword, [userId, newHash]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertAuditLog(_i3.AuditLogsCompanion? log) =>
      (super.noSuchMethod(
            Invocation.method(#insertAuditLog, [log]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.AuditLog>> getRecentAuditLogs({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentAuditLogs, [], {#limit: limit}),
            returnValue: _i5.Future<List<_i3.AuditLog>>.value(<_i3.AuditLog>[]),
          )
          as _i5.Future<List<_i3.AuditLog>>);

  @override
  _i5.Future<int> insertLoginAttempt(_i3.LoginAttemptsCompanion? attempt) =>
      (super.noSuchMethod(
            Invocation.method(#insertLoginAttempt, [attempt]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> cleanOldLoginAttempts(DateTime? cutoff) =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldLoginAttempts, [cutoff]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.LoginAttempt>> getRecentLoginAttempts(
    String? email,
    DateTime? since,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentLoginAttempts, [email, since]),
            returnValue: _i5.Future<List<_i3.LoginAttempt>>.value(
              <_i3.LoginAttempt>[],
            ),
          )
          as _i5.Future<List<_i3.LoginAttempt>>);

  @override
  _i5.Future<int> insertOtp(_i3.OtpRecordsCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#insertOtp, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.OtpRecord?> getLatestValidOtp(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestValidOtp, [email]),
            returnValue: _i5.Future<_i3.OtpRecord?>.value(),
          )
          as _i5.Future<_i3.OtpRecord?>);

  @override
  _i5.Future<void> deleteOtp(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOtp, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> countRecentOtps(String? email, DateTime? since) =>
      (super.noSuchMethod(
            Invocation.method(#countRecentOtps, [email, since]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<List<_i12.StockItem>> watchAllStockItems() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllStockItems, []),
            returnValue: _i5.Stream<List<_i12.StockItem>>.empty(),
          )
          as _i5.Stream<List<_i12.StockItem>>);

  @override
  _i5.Future<int> insertStockItem(_i12.StockItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#insertStockItem, [item]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateStockItem(_i12.StockItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateStockItem, [item]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteStockItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStockItem, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> updateStockItemOrder(List<_i3.StockItemsCompanion>? items) =>
      (super.noSuchMethod(
            Invocation.method(#updateStockItemOrder, [items]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertMaintenanceWithStockCheck(
    _i13.Maintenance? m, {
    int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insertMaintenanceWithStockCheck,
              [m],
              {#userId: userId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMaintenanceWithStockRestoration(
    int? maintenanceId, {
    int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteMaintenanceWithStockRestoration,
              [maintenanceId],
              {#userId: userId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateMaintenanceWithStockAdjustment(
    _i13.Maintenance? newMaintenance, {
    int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMaintenanceWithStockAdjustment,
              [newMaintenance],
              {#userId: userId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i13.Maintenance?> getLastMajorMaintenance(int? terrainId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastMajorMaintenance, [terrainId]),
            returnValue: _i5.Future<_i13.Maintenance?>.value(),
          )
          as _i5.Future<_i13.Maintenance?>);

  @override
  _i5.Future<_i13.Maintenance?> getLastMaintenanceForTerrain(
    int? terrainId, {
    String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLastMaintenanceForTerrain,
              [terrainId],
              {#type: type},
            ),
            returnValue: _i5.Future<_i13.Maintenance?>.value(),
          )
          as _i5.Future<_i13.Maintenance?>);

  @override
  _i5.Future<List<_i14.Terrain>> getAllTerrains() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTerrains, []),
            returnValue: _i5.Future<List<_i14.Terrain>>.value(<_i14.Terrain>[]),
          )
          as _i5.Future<List<_i14.Terrain>>);

  @override
  _i5.Future<_i14.Terrain?> getTerrainById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTerrainById, [id]),
            returnValue: _i5.Future<_i14.Terrain?>.value(),
          )
          as _i5.Future<_i14.Terrain?>);

  @override
  _i5.Future<int> insertTerrain(_i14.Terrain? terrain) =>
      (super.noSuchMethod(
            Invocation.method(#insertTerrain, [terrain]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateTerrain(_i14.Terrain? terrain) =>
      (super.noSuchMethod(
            Invocation.method(#updateTerrain, [terrain]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> updateTerrainStatus(int? terrainId, String? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateTerrainStatus, [terrainId, newStatus]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteTerrain(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTerrain, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i13.Maintenance>> getMaintenancesForTerrain(
    int? terrainId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenancesForTerrain, [terrainId]),
            returnValue: _i5.Future<List<_i13.Maintenance>>.value(
              <_i13.Maintenance>[],
            ),
          )
          as _i5.Future<List<_i13.Maintenance>>);

  @override
  _i5.Stream<List<_i13.Maintenance>> watchMaintenancesInRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchMaintenancesInRange, [start, end]),
            returnValue: _i5.Stream<List<_i13.Maintenance>>.empty(),
          )
          as _i5.Stream<List<_i13.Maintenance>>);

  @override
  _i5.Future<List<_i13.Maintenance>> getMaintenancesInPeriod(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenancesInPeriod, [start, end]),
            returnValue: _i5.Future<List<_i13.Maintenance>>.value(
              <_i13.Maintenance>[],
            ),
          )
          as _i5.Future<List<_i13.Maintenance>>);

  @override
  _i5.Future<_i13.Maintenance?> getMaintenanceById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceById, [id]),
            returnValue: _i5.Future<_i13.Maintenance?>.value(),
          )
          as _i5.Future<_i13.Maintenance?>);

  @override
  _i5.Future<int> insertMaintenance(_i13.Maintenance? m) =>
      (super.noSuchMethod(
            Invocation.method(#insertMaintenance, [m]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateMaintenance(_i3.MaintenancesCompanion? companion) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaintenance, [companion]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteMaintenance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMaintenance, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Stream<List<_i15.AppEvent>> watchAllEvents() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllEvents, []),
            returnValue: _i5.Stream<List<_i15.AppEvent>>.empty(),
          )
          as _i5.Stream<List<_i15.AppEvent>>);

  @override
  _i5.Stream<({int manto, int silice, int sottomanto})> watchSacsTotals({
    int? terrainId,
    int? start,
    int? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchSacsTotals, [], {
              #terrainId: terrainId,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<({int manto, int silice, int sottomanto})>.empty(),
          )
          as _i5.Stream<({int manto, int silice, int sottomanto})>);

  @override
  _i5.Stream<({int manto, int silice, int sottomanto})>
  watchSacsTotalsAllTerrains({
    required Set<int>? terrainIds,
    int? start,
    int? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchSacsTotalsAllTerrains, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<({int manto, int silice, int sottomanto})>.empty(),
          )
          as _i5.Stream<({int manto, int silice, int sottomanto})>);

  @override
  _i5.Stream<List<({int date, int manto, int silice, int sottomanto})>>
  watchDailySeries({required Set<int>? terrainIds, int? start, int? end}) =>
      (super.noSuchMethod(
            Invocation.method(#watchDailySeries, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<
                  List<({int date, int manto, int silice, int sottomanto})>
                >.empty(),
          )
          as _i5.Stream<
            List<({int date, int manto, int silice, int sottomanto})>
          >);

  @override
  _i5.Stream<List<({int manto, int silice, int sottomanto, int weekStart})>>
  watchWeeklySeries({required Set<int>? terrainIds, int? start, int? end}) =>
      (super.noSuchMethod(
            Invocation.method(#watchWeeklySeries, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<
                  List<({int manto, int silice, int sottomanto, int weekStart})>
                >.empty(),
          )
          as _i5.Stream<
            List<({int manto, int silice, int sottomanto, int weekStart})>
          >);

  @override
  _i5.Stream<List<({int manto, int monthStart, int silice, int sottomanto})>>
  watchMonthlySeries({required Set<int>? terrainIds, int? start, int? end}) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthlySeries, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<
                  List<
                    ({int manto, int monthStart, int silice, int sottomanto})
                  >
                >.empty(),
          )
          as _i5.Stream<
            List<({int manto, int monthStart, int silice, int sottomanto})>
          >);

  @override
  _i5.Stream<List<({int date, int manto, int silice, int sottomanto})>>
  watchDailySacsSeriesForTerrains({
    required Set<int>? terrainIds,
    int? start,
    int? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchDailySacsSeriesForTerrains, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<
                  List<({int date, int manto, int silice, int sottomanto})>
                >.empty(),
          )
          as _i5.Stream<
            List<({int date, int manto, int silice, int sottomanto})>
          >);

  @override
  _i5.Stream<({int manto, int silice, int sottomanto})>
  watchMonthlyTotalsByTerrain({
    required int? terrainId,
    required DateTime? anyDay,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthlyTotalsByTerrain, [], {
              #terrainId: terrainId,
              #anyDay: anyDay,
            }),
            returnValue:
                _i5.Stream<({int manto, int silice, int sottomanto})>.empty(),
          )
          as _i5.Stream<({int manto, int silice, int sottomanto})>);

  @override
  _i5.Stream<({int manto, int silice, int sottomanto})>
  watchMonthlyTotalsAllTerrains({
    required Set<int>? terrainIds,
    required DateTime? anyDay,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchMonthlyTotalsAllTerrains, [], {
              #terrainIds: terrainIds,
              #anyDay: anyDay,
            }),
            returnValue:
                _i5.Stream<({int manto, int silice, int sottomanto})>.empty(),
          )
          as _i5.Stream<({int manto, int silice, int sottomanto})>);

  @override
  _i5.Stream<({int manto, int silice, int sottomanto})> watchYearlySacksTotal(
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchYearlySacksTotal, [year]),
            returnValue:
                _i5.Stream<({int manto, int silice, int sottomanto})>.empty(),
          )
          as _i5.Stream<({int manto, int silice, int sottomanto})>);

  @override
  _i5.Stream<List<({int count, int date, String type})>>
  watchDailyMaintenanceTypeCounts({
    required Set<int>? terrainIds,
    int? start,
    int? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchDailyMaintenanceTypeCounts, [], {
              #terrainIds: terrainIds,
              #start: start,
              #end: end,
            }),
            returnValue:
                _i5.Stream<List<({int count, int date, String type})>>.empty(),
          )
          as _i5.Stream<List<({int count, int date, String type})>>);

  @override
  _i5.Future<int> getMaintenanceCount(int? terrainId) =>
      (super.noSuchMethod(
            Invocation.method(#getMaintenanceCount, [terrainId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_19(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_21<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_22<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_23<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_24<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_25<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_26<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_27<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_27<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_28(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_28(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i8.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_29(this, Invocation.getter(#app)),
          )
          as _i6.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i7.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_30(this, Invocation.getter(#settings)),
          )
          as _i7.Settings);

  @override
  set app(_i6.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? _databaseId) => super.noSuchMethod(
    Invocation.setter(#databaseId, _databaseId),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i7.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i8.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_31<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
          )
          as _i8.CollectionReference<Map<String, dynamic>>);

  @override
  _i8.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_32(
              this,
              Invocation.method(#batch, []),
            ),
          )
          as _i8.WriteBatch);

  @override
  _i5.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i8.LoadBundleTask loadBundle(_i16.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_33(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i8.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i8.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i7.GetOptions? options = const _i7.GetOptions(),
    required _i8.FromFirestore<T>? fromFirestore,
    required _i8.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i5.Future<_i8.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_34<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i8.QuerySnapshot<T>>);

  @override
  _i5.Future<_i8.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i7.GetOptions? options = const _i7.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i5.Future<_i8.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_34<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i8.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i8.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_35<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i8.Query<Map<String, dynamic>>);

  @override
  _i5.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i8.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_36<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
          )
          as _i8.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i5.Future<T> runTransaction<T>(
    _i8.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_20<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CollectionReference].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockCollectionReference<T extends Object?> extends _i1.Mock
    implements _i8.CollectionReference<T> {
  MockCollectionReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#path)),
          )
          as String);

  @override
  _i8.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_37(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i8.FirebaseFirestore);

  @override
  Map<String, dynamic> get parameters =>
      (super.noSuchMethod(
            Invocation.getter(#parameters),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<_i8.DocumentReference<T>> add(T? data) =>
      (super.noSuchMethod(
            Invocation.method(#add, [data]),
            returnValue: _i5.Future<_i8.DocumentReference<T>>.value(
              _FakeDocumentReference_36<T>(
                this,
                Invocation.method(#add, [data]),
              ),
            ),
          )
          as _i5.Future<_i8.DocumentReference<T>>);

  @override
  _i8.DocumentReference<T> doc([String? path]) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [path]),
            returnValue: _FakeDocumentReference_36<T>(
              this,
              Invocation.method(#doc, [path]),
            ),
          )
          as _i8.DocumentReference<T>);

  @override
  _i8.CollectionReference<R> withConverter<R extends Object?>({
    required _i8.FromFirestore<R>? fromFirestore,
    required _i8.ToFirestore<R>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withConverter, [], {
              #fromFirestore: fromFirestore,
              #toFirestore: toFirestore,
            }),
            returnValue: _FakeCollectionReference_31<R>(
              this,
              Invocation.method(#withConverter, [], {
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              }),
            ),
          )
          as _i8.CollectionReference<R>);

  @override
  _i8.Query<T> endAtDocument(_i8.DocumentSnapshot<Object?>? documentSnapshot) =>
      (super.noSuchMethod(
            Invocation.method(#endAtDocument, [documentSnapshot]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#endAtDocument, [documentSnapshot]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> endAt(Iterable<Object?>? values) =>
      (super.noSuchMethod(
            Invocation.method(#endAt, [values]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#endAt, [values]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> endBeforeDocument(
    _i8.DocumentSnapshot<Object?>? documentSnapshot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#endBeforeDocument, [documentSnapshot]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#endBeforeDocument, [documentSnapshot]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> endBefore(Iterable<Object?>? values) =>
      (super.noSuchMethod(
            Invocation.method(#endBefore, [values]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#endBefore, [values]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i5.Future<_i8.QuerySnapshot<T>> get([_i7.GetOptions? options]) =>
      (super.noSuchMethod(
            Invocation.method(#get, [options]),
            returnValue: _i5.Future<_i8.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_34<T>(
                this,
                Invocation.method(#get, [options]),
              ),
            ),
          )
          as _i5.Future<_i8.QuerySnapshot<T>>);

  @override
  _i8.Query<T> limit(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#limit, [limit]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#limit, [limit]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> limitToLast(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#limitToLast, [limit]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#limitToLast, [limit]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i5.Stream<_i8.QuerySnapshot<T>> snapshots({
    bool? includeMetadataChanges = false,
    _i7.ListenSource? source = _i7.ListenSource.defaultSource,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#snapshots, [], {
              #includeMetadataChanges: includeMetadataChanges,
              #source: source,
            }),
            returnValue: _i5.Stream<_i8.QuerySnapshot<T>>.empty(),
          )
          as _i5.Stream<_i8.QuerySnapshot<T>>);

  @override
  _i8.Query<T> orderBy(Object? field, {bool? descending = false}) =>
      (super.noSuchMethod(
            Invocation.method(#orderBy, [field], {#descending: descending}),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#orderBy, [field], {#descending: descending}),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> startAfterDocument(
    _i8.DocumentSnapshot<Object?>? documentSnapshot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startAfterDocument, [documentSnapshot]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#startAfterDocument, [documentSnapshot]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> startAfter(Iterable<Object?>? values) =>
      (super.noSuchMethod(
            Invocation.method(#startAfter, [values]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#startAfter, [values]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> startAtDocument(
    _i8.DocumentSnapshot<Object?>? documentSnapshot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startAtDocument, [documentSnapshot]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#startAtDocument, [documentSnapshot]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> startAt(Iterable<Object?>? values) =>
      (super.noSuchMethod(
            Invocation.method(#startAt, [values]),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(#startAt, [values]),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.Query<T> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    Iterable<Object?>? arrayContainsAny,
    Iterable<Object?>? whereIn,
    Iterable<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #where,
              [field],
              {
                #isEqualTo: isEqualTo,
                #isNotEqualTo: isNotEqualTo,
                #isLessThan: isLessThan,
                #isLessThanOrEqualTo: isLessThanOrEqualTo,
                #isGreaterThan: isGreaterThan,
                #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                #arrayContains: arrayContains,
                #arrayContainsAny: arrayContainsAny,
                #whereIn: whereIn,
                #whereNotIn: whereNotIn,
                #isNull: isNull,
              },
            ),
            returnValue: _FakeQuery_35<T>(
              this,
              Invocation.method(
                #where,
                [field],
                {
                  #isEqualTo: isEqualTo,
                  #isNotEqualTo: isNotEqualTo,
                  #isLessThan: isLessThan,
                  #isLessThanOrEqualTo: isLessThanOrEqualTo,
                  #isGreaterThan: isGreaterThan,
                  #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                  #arrayContains: arrayContains,
                  #arrayContainsAny: arrayContainsAny,
                  #whereIn: whereIn,
                  #whereNotIn: whereNotIn,
                  #isNull: isNull,
                },
              ),
            ),
          )
          as _i8.Query<T>);

  @override
  _i8.AggregateQuery count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _FakeAggregateQuery_38(
              this,
              Invocation.method(#count, []),
            ),
          )
          as _i8.AggregateQuery);

  @override
  _i8.AggregateQuery aggregate(
    _i7.AggregateField? aggregateField1, [
    _i7.AggregateField? aggregateField2,
    _i7.AggregateField? aggregateField3,
    _i7.AggregateField? aggregateField4,
    _i7.AggregateField? aggregateField5,
    _i7.AggregateField? aggregateField6,
    _i7.AggregateField? aggregateField7,
    _i7.AggregateField? aggregateField8,
    _i7.AggregateField? aggregateField9,
    _i7.AggregateField? aggregateField10,
    _i7.AggregateField? aggregateField11,
    _i7.AggregateField? aggregateField12,
    _i7.AggregateField? aggregateField13,
    _i7.AggregateField? aggregateField14,
    _i7.AggregateField? aggregateField15,
    _i7.AggregateField? aggregateField16,
    _i7.AggregateField? aggregateField17,
    _i7.AggregateField? aggregateField18,
    _i7.AggregateField? aggregateField19,
    _i7.AggregateField? aggregateField20,
    _i7.AggregateField? aggregateField21,
    _i7.AggregateField? aggregateField22,
    _i7.AggregateField? aggregateField23,
    _i7.AggregateField? aggregateField24,
    _i7.AggregateField? aggregateField25,
    _i7.AggregateField? aggregateField26,
    _i7.AggregateField? aggregateField27,
    _i7.AggregateField? aggregateField28,
    _i7.AggregateField? aggregateField29,
    _i7.AggregateField? aggregateField30,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#aggregate, [
              aggregateField1,
              aggregateField2,
              aggregateField3,
              aggregateField4,
              aggregateField5,
              aggregateField6,
              aggregateField7,
              aggregateField8,
              aggregateField9,
              aggregateField10,
              aggregateField11,
              aggregateField12,
              aggregateField13,
              aggregateField14,
              aggregateField15,
              aggregateField16,
              aggregateField17,
              aggregateField18,
              aggregateField19,
              aggregateField20,
              aggregateField21,
              aggregateField22,
              aggregateField23,
              aggregateField24,
              aggregateField25,
              aggregateField26,
              aggregateField27,
              aggregateField28,
              aggregateField29,
              aggregateField30,
            ]),
            returnValue: _FakeAggregateQuery_38(
              this,
              Invocation.method(#aggregate, [
                aggregateField1,
                aggregateField2,
                aggregateField3,
                aggregateField4,
                aggregateField5,
                aggregateField6,
                aggregateField7,
                aggregateField8,
                aggregateField9,
                aggregateField10,
                aggregateField11,
                aggregateField12,
                aggregateField13,
                aggregateField14,
                aggregateField15,
                aggregateField16,
                aggregateField17,
                aggregateField18,
                aggregateField19,
                aggregateField20,
                aggregateField21,
                aggregateField22,
                aggregateField23,
                aggregateField24,
                aggregateField25,
                aggregateField26,
                aggregateField27,
                aggregateField28,
                aggregateField29,
                aggregateField30,
              ]),
            ),
          )
          as _i8.AggregateQuery);
}

/// A class which mocks [QuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i8.QuerySnapshot<T> {
  MockQuerySnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.QueryDocumentSnapshot<T>> get docs =>
      (super.noSuchMethod(
            Invocation.getter(#docs),
            returnValue: <_i8.QueryDocumentSnapshot<T>>[],
          )
          as List<_i8.QueryDocumentSnapshot<T>>);

  @override
  List<_i8.DocumentChange<T>> get docChanges =>
      (super.noSuchMethod(
            Invocation.getter(#docChanges),
            returnValue: <_i8.DocumentChange<T>>[],
          )
          as List<_i8.DocumentChange<T>>);

  @override
  _i8.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_39(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i8.SnapshotMetadata);

  @override
  int get size =>
      (super.noSuchMethod(Invocation.getter(#size), returnValue: 0) as int);
}

/// A class which mocks [DocumentChange].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentChange<T extends Object?> extends _i1.Mock
    implements _i8.DocumentChange<T> {
  MockDocumentChange() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DocumentChangeType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i7.DocumentChangeType.added,
          )
          as _i7.DocumentChangeType);

  @override
  int get oldIndex =>
      (super.noSuchMethod(Invocation.getter(#oldIndex), returnValue: 0) as int);

  @override
  int get newIndex =>
      (super.noSuchMethod(Invocation.getter(#newIndex), returnValue: 0) as int);

  @override
  _i8.DocumentSnapshot<T> get doc =>
      (super.noSuchMethod(
            Invocation.getter(#doc),
            returnValue: _FakeDocumentSnapshot_40<T>(
              this,
              Invocation.getter(#doc),
            ),
          )
          as _i8.DocumentSnapshot<T>);
}

/// A class which mocks [QueryDocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i8.QueryDocumentSnapshot<T> {
  MockQueryDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i8.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_36<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i8.DocumentReference<T>);

  @override
  _i8.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_39(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i8.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  T data() =>
      (super.noSuchMethod(
            Invocation.method(#data, []),
            returnValue: _i9.dummyValue<T>(this, Invocation.method(#data, [])),
          )
          as T);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}
